server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mq-ingestion-service}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
      ssl.truststore.password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE:PKCS12}
      ssl.keystore.location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      ssl.keystore.password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      ssl.keystore.type: ${KAFKA_SSL_KEYSTORE_TYPE:PKCS12}
      ssl.key.password: ${KAFKA_SSL_KEY_PASSWORD:}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        linger.ms: 5
ibm:
  mq:
    queue-manager: ${IBM_MQ_QUEUE_MANAGER:QM1}
    channel: ${IBM_MQ_CHANNEL:DEV.APP.SVRCONN}
    conn-name: ${IBM_MQ_CONN_NAME:ibm-mq:1414}
    queue: ${IBM_MQ_QUEUE:PAYMENT.QUEUE}
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:change-me}
    ssl:
      enabled: ${IBM_MQ_SSL_ENABLED:false}
      cipher-suite: ${IBM_MQ_SSL_CIPHER_SUITE:}
      peer-name: ${IBM_MQ_SSL_PEER_NAME:}
      fips-required: ${IBM_MQ_SSL_FIPS_REQUIRED:false}
      trust-store-location: ${IBM_MQ_SSL_TRUSTSTORE_LOCATION:}
      trust-store-password: ${IBM_MQ_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-type: ${IBM_MQ_SSL_TRUSTSTORE_TYPE:PKCS12}
      key-store-location: ${IBM_MQ_SSL_KEYSTORE_LOCATION:}
      key-store-password: ${IBM_MQ_SSL_KEYSTORE_PASSWORD:}
      key-store-type: ${IBM_MQ_SSL_KEYSTORE_TYPE:PKCS12}
app:
  region: ${APP_KAFKA_REGION:EMEA}
  kafka:
    topic: ${APP_KAFKA_TOPIC:raw-payments-emea}
  jms:
    concurrency: ${SPRING_JMS_LISTENER_CONCURRENCY:3-6}
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
