apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking-aspac
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: banking
    patch: |-
      - op: replace
        path: /metadata/name
        value: banking-aspac
configMapGenerator:
  - name: banking-config
    behavior: replace
    literals:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_KAFKA_REGION=ASPAC
      - APP_KAFKA_RAW_TOPIC=raw-payments-aspac
      - APP_KAFKA_OUTPUT_TOPIC=json-payments-aspac
      - APP_KAFKA_DLQ_TOPIC=dlq-payments-aspac
      - KAFKA_CONSUMER_GROUP=payment-processor-aspac
      - IBM_MQ_QUEUE_MANAGER=QM1
      - IBM_MQ_CHANNEL=DEV.APP.SVRCONN
      - IBM_MQ_CONN_NAME=ibm-mq-aspac:1414
      - IBM_MQ_QUEUE=PAYMENT.QUEUE.ASPAC
generatorOptions:
  disableNameSuffixHash: true
