apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlq-replay
  namespace: banking
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dlq-replay
  template:
    metadata:
      labels:
        app: dlq-replay
        app.kubernetes.io/part-of: kafka-banking
    spec:
      serviceAccountName: banking-app
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 45
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: dlq-replay
      containers:
        - name: dlq-replay
          image: ghcr.io/anchalkohli/kafka-banking-dlq-replay:main
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: banking-config
            - secretRef:
                name: banking-secrets
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: KEYCLOAK_ISSUER_URI
              value: http://keycloak:8080/realms/banking
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: /etc/banking/tls/kafka-truststore.p12
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: /etc/banking/tls/kafka-keystore.p12
          volumeMounts:
            - name: banking-tls
              mountPath: /etc/banking/tls
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            periodSeconds: 20
            timeoutSeconds: 3
      volumes:
        - name: banking-tls
          secret:
            secretName: banking-tls
            optional: true
            defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: dlq-replay
  namespace: banking
spec:
  selector:
    app: dlq-replay
  ports:
    - port: 8085
      targetPort: 8085
