apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-processor
  namespace: banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-processor
  template:
    metadata:
      labels:
        app: kafka-processor
        app.kubernetes.io/part-of: kafka-banking
    spec:
      containers:
        - name: kafka-processor
          image: ghcr.io/anchalkohli/kafka-processor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: banking-config
          env:
            - name: APP_KAFKA_INPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: APP_KAFKA_RAW_TOPIC
            - name: SERVER_PORT
              value: "8082"
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-processor
  namespace: banking
spec:
  selector:
    app: kafka-processor
  ports:
    - port: 8082
      targetPort: 8082
