apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret-example.yaml
  - mq-ingestion-deployment.yaml
  - kafka-processor-deployment.yaml
  - dlq-replay-deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
