apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-ingestion
  namespace: banking
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: mq-ingestion
  template:
    metadata:
      labels:
        app: mq-ingestion
        app.kubernetes.io/part-of: kafka-banking
    spec:
      serviceAccountName: banking-app
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 45
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: mq-ingestion
      containers:
        - name: mq-ingestion
          image: ghcr.io/anchalkohli/kafka-banking-mq-ingestion:main
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: banking-config
            - secretRef:
                name: banking-secrets
          env:
            - name: APP_KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: APP_KAFKA_RAW_TOPIC
            - name: SPRING_APPLICATION_NAME
              value: mq-ingestion
            - name: SERVER_PORT
              value: "8081"
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 20
            timeoutSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: mq-ingestion
  namespace: banking
spec:
  selector:
    app: mq-ingestion
  ports:
    - port: 8081
      targetPort: 8081
