apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking-emea
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: banking
    patch: |-
      - op: replace
        path: /metadata/name
        value: banking-emea
configMapGenerator:
  - name: banking-config
    behavior: replace
    literals:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_KAFKA_REGION=EMEA
      - APP_KAFKA_RAW_TOPIC=raw-payments-emea
      - APP_KAFKA_OUTPUT_TOPIC=json-payments-emea
      - APP_KAFKA_DLQ_TOPIC=dlq-payments-emea
      - KAFKA_CONSUMER_GROUP=payment-processor-emea
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_SSL_TRUSTSTORE_TYPE=PKCS12
      - KAFKA_SSL_KEYSTORE_TYPE=PKCS12
      - KAFKA_SASL_MECHANISM=PLAIN
      - IBM_MQ_QUEUE_MANAGER=QM1
      - IBM_MQ_CHANNEL=DEV.APP.SVRCONN
      - IBM_MQ_CONN_NAME=ibm-mq-emea:1414
      - IBM_MQ_QUEUE=PAYMENT.QUEUE.EMEA
      - IBM_MQ_SSL_ENABLED=false
      - IBM_MQ_SSL_FIPS_REQUIRED=false
      - IBM_MQ_SSL_TRUSTSTORE_TYPE=PKCS12
      - IBM_MQ_SSL_KEYSTORE_TYPE=PKCS12
generatorOptions:
  disableNameSuffixHash: true
